### ISSUE TITLE
T420d - temperature jumps, oryginal JBC C115-120

### ISSUE THREAD

**Issue by euzebb** [aixun-updates/aixun-updates-src#3]
Hi,

Soft version: 1.23
Station: T420d
Oryginal JBC C115-120.

The temperature jumps at standby between 90-132/139 load from 0-full. When operating at the set 350 degrees Celsius, the temperature jumps to 350-397~, load the same.
I have two of these and both don't work. Checked at the JBC station - they work properly. Other heaters work properly.

**Comment by dd010101** [comment]
This isn't AiXun support page - this is unofficial 3rd-party project. Please [contact AiXun](https://www.aixuntech.com/contact/) instead if you want support.
