### ISSUE TITLE
AiXun T3AS firmware update to v1.36

### ISSUE THREAD

**Issue by magnificu** [aixun-updates/aixun-updates-src#4]
It seems that the firmware file (v1.36) provided is valid for T3A and not for T3AS and therefore the update fails on T3AS. 
Please provide a valid firmware for T3AS.

https://aixun-updates.github.io/#t3as

**Comment by dd010101** [comment]
~Seems like mistake on AiXun side? I do see this in more instances where they post A firmware for AS device like in B vs BS. Either way this is all they uploaded so I don't have anything else. You can try official app it should fail as well to upgrade firmware.~

EDIT: I do see now that there is no T3AS 1.36 record at all nor there is T3AS 1.36 bin file at all, nor 1.35 so I'm not quite sure what is going on but it looks funny, by the result that AiXun returns there is no bin file at all, thus I have no idea where to get it.

**Comment by dd010101** [comment]
Never mind I found it. How the swap happened I'm not quite sure but now it works so... I removed all the different old APIs so this should not happen again. Seems like the old/legacy APIs did override the new API.

Thanks for letting me know.
