### ISSUE TITLE
Something goes wrong in the solder-tip temperature measurement routines

### ISSUE THREAD

**Issue by ADE-Elec** [aixun-updates/aixun-updates-src#6]
Hello,

When the solder-tip has less copper mass and so heating up to fast for the firmware to measure, the temperature measure overflows and the system keeps on heating the tip until it gets literally red hot!

New to fix this as it is very dangerous like how it is implemented in your firmware now, I check with the latest firmware and also this problem is in this too!

Regards

Alexander

**Comment by randybb** [comment]
This project has nothing to do with aixun company, it is just pulling data and showing which versions for their products are available.

**Comment by ADE-Elec** [comment]
Sorry can you point me to the right locations?Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Roman Priesol ***@***.***> Datum: 19-11-2024  16:29  (GMT+01:00) Aan: aixun-updates/aixun-updates-src ***@***.***> Cc: ADE-Elec ***@***.***>, Author ***@***.***> Onderwerp: Re: [aixun-updates/aixun-updates-src] Something goes wrong in the solder-tip temperature measurement routines (Issue #6) 
You are on the wrong place. This project has nothing to do with aixun company, it is just pulling data and showing which versions for their products are available.

**Comment by randybb** [comment]
https://aixun.com/contact/  but I have no clue how flexible they are :D

**Comment by dd010101** [comment]
Indeed. This isn't AiXun support page - this is unofficial 3rd-party project. Please [contact AiXun](https://aixun.com/contact/) instead if you want support.
